const keywordMapping = {
  "dry fruits": "dry fruits",
  "dryfruit online": "dry fruits",
  "dry fruits shop": "dry fruits",
  "mixed dry fruits": "dry fruits",
  "premium dry fruits": "dry fruits",
  "healthy dry fruits": "dry fruits",
  "cashews": "cashew",
  "cashew nuts": "cashew",
  "kaju": "cashew",
  "cashew dry fruit": "cashew",
  "raw cashews": "raw cashew",
  "roasted cashews": "roasted cashew",
  "salted cashews": "salted cashew",
  "plain cashews": "plain cashew",
  "organic cashews": "organic cashew",
  "redclay cashews": "cashew",
  "redclay dry fruits": "dry fruits",
  "red clay cashew nuts": "cashew",
  "redclay kaju": "cashew",
  "redclay cashews online": "cashew",
  "buy cashews online": "cashew",
  "cashews price": "cashew",
  "cashew nuts 1kg price": "cashew",
  "best cashews online": "cashew",
  "premium cashews": "cashew",
  "fresh cashews": "cashew",
  "cashews home delivery": "cashew",
  "healthy snacks": "dry fruits",
  "protein dry fruits": "dry fruits",
  "dry fruits for weight gain": "dry fruits",
  "dry fruits for kids": "dry fruits",
  "dry fruits for gifting": "dry fruits",
  "kaju online": "cashew",
  "kaju price today": "cashew",
  "best kaju brand": "cashew",
  "cashew shop near me": "cashew"
}


module.exports = keywordMapping;